slam_toolbox:
  ros__parameters:

    # Mode
    slam_mode: "mapping"     # always mapping, no localization-only

    # Frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan

    # Use filtered odom from EKF
    odom_topic: /odometry/filtered

    # general
    use_sim_time: false
    throttle_scans: 1
    transform_timeout: 0.2
    update_rate: 5.0
    publish_period: 1.0
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.5
    map_save_path: /home/user/maps/
